[package]
name = "paudio-dlna"
version = "0.1.0"
authors = ["Ishan Jain <ishanjain28@gmail.com>"]

[dependencies]
chrono = "0.4.0"
slog-term = "2.3.0"
slog = "2.1.1"
regex = "0.2.6"
lazy_static = "1.0.0"
dbus = "0.6.1"
